#!/bin/bash

SCRIPT_DIR=$(readlink -f $(dirname ${BASH_SOURCE[0]}))

# Set gnats port
GNATS_PORT=${GNATS_PORT:-4222}
# The port is from the env variable from flynn port env
GNATS_MONITOR_PORT=${PORT}

GNATS_CLUSTER_PORT=${GNATS_CLUSTER_PORT:-6222}
GNATS_AUTZ_USER=${GNATS_AUTZ_USER:-ruser}
GNATS_AUTZ_PASS=${GNATS_AUTZ_PASS:-T0pS3cr3t}
GNATS_AUTZ_TIMEOUT=${GNATS_AUTZ_TIMEOUT:-2}

cat >>${SCRIPT_DIR}/gnatsd.conf <<-EOCONF
# Client port of 4222 on all interfaces
port: ${GNATS_PORT}

# HTTP monitoring port
monitor_port: ${GNATS_MONITOR_PORT}

# This is for clustering multiple servers together.
cluster {

  # Route connections to be received on any interface on port 6222
  port: ${GNATS_CLUSTER_PORT}

  # Routes are protected, so need to use them with --routes flag
  # e.g. --routes=nats-route://ruser:T0pS3cr3t@otherdockerhost:6222
  authorization {
    user: ${GNATS_AUTZ_USER}
    password: ${GNATS_AUTZ_PASS}
    timeout: ${GNATS_AUTZ_TIMEOU}
  }

  # Routes are actively solicited and connected to from this server.
  # This Docker image has none by default, but you can pass a
  # flag to the gnatsd docker image to create one to an existing server.
  routes = []
}
EOCONF

exec ${SCRIPT_DIR}/gnatsd -c ${SCRIPT_DIR}/gnatsd.conf
